name: Auto-merge when change is ready

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  merge_pr:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"