name: Deploy to preview

on:
  pull_request

jobs: 
  build_preview:
    if: ${{github.event.pull_request.draft == true}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build
      
      - name: Deploy to Firebase
        id: firebase_deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FANCY_SPIRITS }}'
          channelId: ${{ github.event.pull_request.head.ref }}
          projectId: fancy-spirits
          expires: 2d
      
      - name: Add Comment for Preview URL
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Preview is available at ${{ steps.firebase_deploy.outputs.urls }}